resolver: lts-7.10
packages:
    - 'wl-pprint'
    # - 'wl-pprint-ansi'
    # - 'wl-pprint-compat-old-wl-pprint'
    # - 'wl-pprint-compat-old-wl-pprint-ansi'
extra-deps: []
flags: {}
extra-package-dbs: []
